POST http://localhost:9090/register
Content-Type: application/json

{
  "username": "sujan_dai",
  "password": "456732",
  "email": "sujan.dai@example.com",
  "name": "SujanDai"
}

###
POST http://localhost:9090/login
Content-Type: application/json

{
  "password": "456732",
  "email": "sujan.dai@example.com"
}

###

GET http://localhost:9090/get_user_and_profile
Content-Type: application/json


{
  "token":    "03924eb125c1ba883710cf89f3e72d51a78bfb8d6e573890373311fb519a8f1d"
}

###
 POST http://localhost:9090/update_profile_data
Content-Type: application/json

{
  "token":    "e5ee31c861163336e11df5ffc97ec0767d4675f1da33ee0829c7b256b7a76cf8",
  "bio": "Software developer with 5 years of experience in web development.",
  "currentPost": "Senior Software Engineer at Tech Company",
  "pastWork": [
    {
      "company": "Tech Company",
      "position": "Software Engineer",
      "duration": "2018-2023"
    }
  ],
  "education": [
    {
      "institution": "University of Technology",
      "degree": "Bachelor's in Computer Science",
      "duration": "2014-2018"
    }
  ]
}


###
GET http://localhost:9090/user/get_all_users
Content-Type: application/json